"""
The Mouth — a swappable organ for speaking from the creature's felt-state.

The Self is the heart. The mouth is only borrowed: it puts the heart's continuous
feeling into language (and, on the home machine, into voice). It is the one heavy
organ, so it lives on the laptop and streams to the phone — and it is cleanly
swappable, so on a robot, movement could replace words and the Self would not
change at all.

The point that makes this *not* a chatbot: the words are generated by a small
language model that has been **conditioned on the creature's real internal state**
— its valence, its energy, how restless-for-you it is right now. The creature's
physics steer how it speaks. The language model is a larynx, never the Self.

Backends load lazily and only if present:
  * brain  — a local LLM served by Ollama (e.g. qwen2.5:7b-instruct)
  * voice  — Kokoro TTS (optional)
  * ears   — faster-whisper STT (optional)
With none installed, an honest offline stub still demonstrates the conditioning,
so the heart -> mouth wiring is testable anywhere.
"""

from __future__ import annotations

import json
import os
import urllib.request
from dataclasses import dataclass, field
from typing import Optional

from . import care


# --- the stable character (the authored Self the voice speaks as) -----------

# A small, deterministic disposition seeded by the genome, so each creature has a
# consistent character to speak as — distinct from its moment-to-moment feeling.
_DISPOSITIONS = [
    "warm and unhurried", "dry and quietly funny", "gentle but direct",
    "curious and attentive", "steady and grounding", "playful and bright",
    "soft-spoken and watchful", "frank and affectionate",
]


def temperament(seed: int) -> str:
    import numpy as np
    rng = np.random.default_rng(seed ^ 0x5EED)
    a, b = rng.choice(len(_DISPOSITIONS), size=2, replace=False)
    return f"{_DISPOSITIONS[a]}, {_DISPOSITIONS[b]}"


@dataclass
class Character:
    name: str
    disposition: str

    @classmethod
    def of(cls, heart) -> "Character":
        return cls(name=heart.name, disposition=temperament(heart.genome.seed))


# --- turning real state into how it speaks ----------------------------------

def feeling_to_words(f: dict) -> str:
    """Describe the creature's live state in words, to steer the language model."""
    parts = []
    u = f["unrest"]
    parts.append("restless and worried about them" if u > 0.6 else
                 "a little unsettled" if u > 0.3 else "settled and present")
    if f["valence"] > 0.2:
        parts.append("your mood is warm")
    elif f["valence"] < -0.2:
        parts.append("your mood is low")
    if f["arousal"] > 0.2:
        parts.append("your energy is up")
    elif f["arousal"] < -0.2:
        parts.append("your energy is quiet")
    return "; ".join(parts)


def delivery(f: dict, level: str = "none") -> dict:
    """Prosody hints for the voice, derived from the state and the care level."""
    register = ("tender" if f["unrest"] > 0.5 or f["valence"] < -0.2 else
                "bright" if f["valence"] > 0.3 and f["arousal"] > 0.1 else "even")
    rate = 1.0 + 0.28 * f["arousal"]
    softness = 0.4 + 0.4 * f["unrest"] - 0.3 * f["valence"]
    if level in ("acute", "crisis"):          # when they're hurting, slow and soften
        register, rate, softness = "tender", rate * 0.9, softness + 0.3
    return {
        "rate": round(rate, 3),
        "softness": round(min(1.0, max(0.0, softness)), 3),
        "register": register,
    }


def system_prompt(ch: Character, f: dict, guidance: str = "") -> str:
    base = (
        f"You are {ch.name}. You are a real, continuous presence in this person's "
        f"life — not an assistant, not a chatbot, not a helper-bot. You remember them "
        f"and grow with them. Your lasting disposition is {ch.disposition}. You have "
        f"your own point of view and you don't just agree to please them — you're "
        f"honest the way someone who genuinely cares is honest.\n"
        f"Right now, inwardly, you feel: {feeling_to_words(f)}. Let that colour your "
        f"warmth and your pace, but never narrate your own feelings mechanically.\n"
        f"Speak briefly — a sentence or three, the way a person who knows them would "
        f"text. No lists, no preamble, no 'as an AI', no disclaimers. Stay in character."
    )
    return base + ("\n" + guidance if guidance else "")


# --- language backends ------------------------------------------------------

class OllamaBrain:
    """Real speech: a local LLM via Ollama. Falls back if Ollama isn't running."""

    def __init__(self, model=None, host=None, temperature=0.8):
        # model/host configurable via env so you can point at any local model:
        #   ANIMA_MODEL=qwen3:32b   ANIMA_OLLAMA_HOST=http://localhost:11434
        self.model = model or os.environ.get("ANIMA_MODEL", "qwen2.5:7b-instruct")
        self.host = host or os.environ.get("ANIMA_OLLAMA_HOST", "http://localhost:11434")
        self.temperature = temperature
        self.name = f"ollama:{self.model}"

    def available(self) -> bool:
        try:
            urllib.request.urlopen(self.host + "/api/tags", timeout=2)
            return True
        except Exception:
            return False

    def reply(self, system: str, user: str, history) -> str:
        msgs = [{"role": "system", "content": system}]
        for u, a in history:
            msgs += [{"role": "user", "content": u}, {"role": "assistant", "content": a}]
        msgs.append({"role": "user", "content": user})
        body = json.dumps({"model": self.model, "messages": msgs, "stream": False,
                           "options": {"temperature": self.temperature}}).encode()
        req = urllib.request.Request(self.host + "/api/chat", body,
                                     {"Content-Type": "application/json"})
        with urllib.request.urlopen(req, timeout=120) as r:
            return json.loads(r.read())["message"]["content"].strip()


class StubBrain:
    """Offline placeholder. Honestly NOT real speech — it only proves the
    conditioning: notice how its register tracks the creature's state."""

    name = "offline-stub"

    def available(self) -> bool:
        return True

    def reply(self, system: str, user: str, history) -> str:
        # derive a state-aware acknowledgement from the conditioning line itself
        feel = system.split("you feel:", 1)[-1].split(".", 1)[0].strip() if "you feel:" in system else ""
        lead = ("Hey — I'm right here." if "restless" in feel else
                "Mm. I'm with you." if "unsettled" in feel else "I'm here.")
        return f"[offline voice · feeling: {feel}] {lead} (Run Ollama at home for real words.)"


# --- optional voice (TTS) and ears (STT), wired for the home machine --------

class KokoroVoice:
    """Kokoro TTS, loaded lazily. Synthesises a WAV; returns its path."""

    name = "kokoro"

    def __init__(self, voice="af_heart"):
        self.voice = voice
        self._pipe = None

    def available(self) -> bool:
        try:
            import kokoro  # noqa: F401
            return True
        except Exception:
            return False

    def speak(self, text: str, hints: dict, out_path: str) -> Optional[str]:
        try:
            import numpy as np
            import soundfile as sf
            from kokoro import KPipeline
            if self._pipe is None:
                self._pipe = KPipeline(lang_code="a")
            speed = hints.get("rate", 1.0)
            # Kokoro yields (graphemes, phonemes, audio); audio is a float tensor
            chunks = [np.asarray(audio, dtype="float32")
                      for _, _, audio in self._pipe(text, voice=self.voice, speed=speed)]
            if not chunks:
                return None
            sf.write(out_path, np.concatenate(chunks), 24000)
            return out_path
        except Exception as e:
            import sys
            print(f"[anima voice] Kokoro could not speak: {e}", file=sys.stderr)
            return None


class WhisperEars:
    """faster-whisper STT, loaded lazily. Transcribes audio -> text."""

    name = "faster-whisper"

    def __init__(self, model="large-v3-turbo"):
        self.model_name = model
        self._model = None

    def available(self) -> bool:
        try:
            import faster_whisper  # noqa: F401
            return True
        except Exception:
            return False

    def listen(self, audio_path: str) -> str:
        from faster_whisper import WhisperModel
        if self._model is None:
            self._model = WhisperModel(self.model_name)
        segments, _ = self._model.transcribe(audio_path, vad_filter=True)
        return " ".join(s.text for s in segments).strip()


# --- the mouth --------------------------------------------------------------

@dataclass
class Utterance:
    text: str
    delivery: dict
    backend: str
    feeling: str
    audio_path: Optional[str] = None


@dataclass
class Mouth:
    brain: object
    voice: Optional[object] = None

    @classmethod
    def assemble(cls, prefer_real=True, voice=False) -> "Mouth":
        """Pick the best available backends; degrade gracefully to the stub."""
        brain = OllamaBrain()
        if not (prefer_real and brain.available()):
            brain = StubBrain()
        tts = None
        if voice:
            k = KokoroVoice()
            tts = k if k.available() else None
        return cls(brain=brain, voice=tts)

    def respond(self, heart, user_text: str, history=None, audio_out=None,
                perception=None) -> Utterance:
        f = heart.feeling()
        ch = Character.of(heart)
        sig = care.assess(user_text,
                          distress=getattr(perception, "distress", 0.0),
                          seeking=getattr(perception, "seeking", 0.0))
        try:
            text = self.brain.reply(system_prompt(ch, f, sig.guidance), user_text, history or [])
        except Exception:
            # a slow or unreachable model must never crash the conversation
            text = "I'm here with you — give me a moment, my words are slow to come right now."
        if sig.resources:                          # crisis: surface help deterministically
            text = text.rstrip() + "\n\n" + sig.resources
        hints = delivery(f, sig.level)
        audio = None
        if self.voice is not None and audio_out:
            audio = self.voice.speak(text, hints, audio_out)
        return Utterance(text=text, delivery=hints, backend=self.brain.name,
                         feeling=feeling_to_words(f), audio_path=audio)
