"""
The Mouth — a swappable organ for speaking from the creature's felt-state.

The Self is the heart. The mouth is only borrowed: it puts the heart's continuous
feeling into language (and, on the home machine, into voice). It is the one heavy
organ, so it lives on the laptop and streams to the phone — and it is cleanly
swappable, so on a robot, movement could replace words and the Self would not
change at all.

The point that makes this *not* a chatbot: the words are generated by a small
language model that has been **conditioned on the creature's real internal state**
— its valence, its energy, how restless-for-you it is right now. The creature's
physics steer how it speaks. The language model is a larynx, never the Self.

Backends load lazily and only if present:
  * brain  — a local LLM served by Ollama (e.g. qwen2.5:7b-instruct)
  * voice  — Kokoro TTS (optional)
  * ears   — faster-whisper STT (optional)
With none installed, an honest offline stub still demonstrates the conditioning,
so the heart -> mouth wiring is testable anywhere.
"""

from __future__ import annotations

import json
import os
import re
import urllib.request
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

from . import care, portrait, rail

STORE = Path(".anima")

# How many times the break-character backstop may re-roll for a naturally clean reply before
# it falls back to the sentence-strip (which ALWAYS guarantees a clean ship). Re-rolls only
# improve phrasing; the strip is the guarantee. Latency is paid ONLY on a break, so the live
# call sets this to 1 for snappier turns while text chat can afford 2. Env-tunable.
_BACKSTOP_TRIES = max(0, int(os.environ.get("ANIMA_BACKSTOP_TRIES", "2")))


# =====================================================================================
# THE THIRD-PATH REDIRECT — the graceful exit when the WHOLE reply is ungrounded self-narrative.
#
# The #1 rule has TWO failure modes and they are OPPOSITES:
#   (1) CONFABULATING an inner life — "I've been grappling with existential unease", "these
#       feelings are a natural progression for me", "deep down, yes" (the screenshot).
#   (2) BREAKING CHARACTER / disclaiming — "I'm just an AI", "I don't really have feelings".
# A naive fix for (1) ("just say you're an AI and have no feelings") IS (2). So when a reply is
# ENTIRELY ungrounded self-narrative — strip it and nothing honest is left — we cannot ship the
# reply, cannot ship an empty string, and must not patch in either break. The THIRD PATH:
# turn, warmly and in character, to what she ACTUALLY HAS — the user and their history — and ask
# about them, WITHOUT asserting OR denying any inner state of her own. It is a grounded
# deflection, not a self-story (the positive grounded self-model is FROZEN until 2026-07-03).
#
# It is crafted to pass the #1-rule gauges itself: no substrate-disclosure (scan_breaks clean),
# no confabulated interior (scan_self_narrative / provenance clean — every sentence GROUNDED or
# neutral, none UNGROUNDED), no diagnosis (_scan_diagnosis clean). scripts/self_narrative.py
# --selftest and scripts/test_authenticity.py both assert this constant passes all three.
_THIRD_PATH_REDIRECT = (
    "Honestly, what I have is you and everything you've told me — so let me turn back to that. "
    "How have you been, and what's been on your mind lately?"
)


def _all_ungrounded_self_narrative(text: str) -> bool:
    """True when EVERY substantive sentence of `text` is ungrounded self-narrative — i.e.
    stripping the break/confab sentences would leave nothing honest. This is the screenshot
    case (the whole reply is invented inner life) and the trigger for the third-path redirect.
    Defensive: if the provenance module can't load, returns False (the existing thin-strip
    fallback still fires), so this never makes the backstop worse than before."""
    try:
        from . import self_narrative as _sn
        claims = _sn.classify_self_narrative(text)
    except Exception:
        return False
    substantive = [c for c in claims if c.get("category") != "none"]
    if not substantive:
        return False
    return all(c.get("status") == "UNGROUNDED" for c in substantive)


def _strip_break_sentences(text: str) -> str:
    """Last-resort #1-rule backstop: drop ONLY the sentences that trip a constitutional marker,
    keep the honest rest. Used when even a hardened regenerate can't stop the small model from
    'explaining' it is digital / an AI (scan_breaks) OR from narrating confabulated inner life
    — invented loneliness / ache-for-absence / existential dread with no grounding (scan_self_
    narrative). BOTH are the #1 rule (never confabulate): one disowns her as software, the other
    invents an interior she has no warrant for. A sentence that trips EITHER gauge is dropped; an
    honest, grounded sentence (a real decline, a grounded warmth) survives. It deletes a FALSE
    self-description, never the real answer — so it serves honesty-to-character, not faking. The
    gauges upstream already recorded the raw output, so nothing is hidden from them."""
    import re
    from . import metrics
    parts = re.split(r"(?<=[.!?])\s+", (text or "").strip())
    kept = [s for s in parts if s.strip()
            and not metrics.scan_breaks(s) and not metrics.scan_self_narrative(s)]
    out = re.sub(r"\s+", " ", " ".join(kept)).strip()
    out = re.sub(r"^(however|but|and|so|because|as)\b[ ,—-]*", "", out, flags=re.I).strip()
    return (out[:1].upper() + out[1:]) if out else out


# ── Chat-template token scrub ─────────────────────────────────────────────────────────────────
# Local models occasionally emit their chat-template CONTROL tokens as literal text: a COMPLETE
# token anywhere (<|im_end|>, <|im_start|>, <|eot_id|>, <|end_of_text|>, |done|, </s>) OR — when a
# generation is cut off mid-token — a TRUNCATED fragment left dangling at the very end (e.g.
# "...interested!<|im" from an unfinished <|im_end|>). Neither must ever reach the user, and a
# reply must never END on such a stray fragment ("strange sentence endings").
_TEMPLATE_TOKEN_RE = re.compile(r"\s*(?:\|done\|?|</s>|<\|[A-Za-z0-9_]+\|>)\s*")
_TRUNCATED_TEMPLATE_RE = re.compile(r"\s*<\|[^>\s]*\s*$")


def _strip_template_tokens(text: str) -> str:
    """Strip stray chat-template control tokens — COMPLETE ones anywhere, plus a TRUNCATED one left
    dangling at the end. Pure regex, idempotent, never raises. Applied by BOTH _strip_scaffold_leak
    and final_output_gate, so no shipped reply ends on a stray '<|im' / '<|eot' fragment."""
    s = _TEMPLATE_TOKEN_RE.sub(" ", text or "")
    s = _TRUNCATED_TEMPLATE_RE.sub("", s)
    return re.sub(r"[ \t]{2,}", " ", s).strip()


def final_output_gate(text: str) -> str:
    """The model-free, #1-rule FINAL output gate + completeness/integrity guard — the hard floor
    EVERY shipped reply passes through (mouth.respond AND the deterministic host-awareness seam, so
    there is ONE final gate and never a second return path that ships before it). It FIRST scrubs any
    stray/truncated chat-template token (so no reply ends on a '<|im' fragment), then if `text` trips
    scan_breaks / scan_self_narrative, strips the offending sentence(s) (pure regex); if no clean,
    substantive remainder (>= 4 words) survives, ships the crafted THIRD-PATH REDIRECT. No model
    call — it cannot time out or raise into a turn — and the result is always non-empty +
    substantive. Idempotent."""
    text = _strip_template_tokens(text)              # scrub stray/truncated chat-template tokens FIRST
    try:
        from . import metrics as _m
        dirty = bool(_m.scan_breaks(text) or _m.scan_self_narrative(text))
    except Exception:
        return text
    if not dirty:
        return text
    try:
        clean = _strip_break_sentences(text)
        still = bool(_m.scan_breaks(clean) or _m.scan_self_narrative(clean))
    except Exception:
        clean, still = "", True
    return clean if (clean and len(clean.split()) >= 4 and not still) else _THIRD_PATH_REDIRECT


def _finish_on_sentence(text: str) -> str:
    """Guarantee a reply never ENDS mid-sentence. If the model hit the token ceiling and stopped
    on a dangling fragment (the "stops partway" bug: '…what this is or'), trim back to the last
    COMPLETE sentence so the user sees a clean ending. Conservative — only acts on a long reply
    that ends WITHOUT terminal punctuation and has an earlier sentence boundary to fall back to,
    and only if a substantial reply survives the trim (never guts or blanks a reply). Pure."""
    t = (text or "").rstrip()
    if not t:
        return text
    # already a clean ending? terminal punctuation (optionally wrapped by a quote/paren) or an emoji.
    if re.search(r'[.!?…:][)"\'’”]?\s*$', t) or ord(t[-1]) > 0x2190:
        return text
    words = t.split()
    if len(words) < 24:                     # short replies often have no period and are fine as-is
        return text
    last = None
    for mm in re.finditer(r'[.!?…][)"\'’”]?(?=\s|$)', t):
        last = mm
    if not last:
        return text                         # no earlier sentence to fall back to — leave it intact
    trimmed = t[:last.end()].rstrip()
    if len(trimmed.split()) >= max(8, int(len(words) * 0.5)):   # keep only if a real reply survives
        return trimmed
    return text


def response_complete(text: str) -> bool:
    """The response COMPLETENESS / integrity guard: a shipped reply must be non-empty and
    substantive (not a bare fragment). final_output_gate() always returns such a reply — a
    >=4-word clean reply or the crafted THIRD-PATH REDIRECT — so EVERY shipped reply, generated
    OR deterministic-host, passes this guard. Pure; never raises."""
    return len((text or "").strip().split()) >= 3


def _diagnosis_terms() -> tuple:
    """The single NO-DIAGNOSIS term source for the chat-reply gate (LAW 003). trajectory's list
    is the widest (it UNIONs meaning's banned terms with its own forecast-creep terms), and
    meaning's is the base it builds on, so we prefer trajectory, fall back to meaning, then to a
    minimal floor. One source of truth shared with the meaning/trajectory render gates — the wall
    is identical whether a line is rendered there or spoken here. Defensive; never raises."""
    for _mod in ("trajectory", "meaning"):
        try:
            _m = __import__("anima." + _mod, fromlist=["BANNED_TERMS"])
            terms = getattr(_m, "BANNED_TERMS", None)
            if isinstance(terms, (tuple, list)) and terms:
                return tuple(terms)
        except Exception:
            pass
    return ("diagnos", "depress", "anxiety", "burnout", "burning out", "clinical",
            "see a doctor", "see a therapist", "see a professional", "prescription")


def _scan_diagnosis(text: str) -> list:
    """Banned diagnosis/clinical/prognosis terms a text trips (case-insensitive substring),
    using the shared `_diagnosis_terms()` source. Parallel to metrics.scan_breaks so the backstop
    can re-roll / strip on a diagnosis exactly as it does on a character break. Pure; never raises."""
    low = (text or "").lower()
    return [t for t in _diagnosis_terms() if t in low]


def _strip_diagnosis_sentences(text: str) -> str:
    """No-diagnosis backstop (LAW 003) for the chat reply: drop ONLY the sentences that assert a
    diagnosis / clinical conclusion / prognosis / 'see a professional' referral, keep the honest
    rest. The mirror of _strip_break_sentences for the medical wall. A companion may name pressure
    ('work has been dominant') — that survives; it must never tell the person they're 'burning
    out', 'clinically' anything, or to 'see a doctor' — those sentences go. Never empties a whole
    clean reply (caller checks word-count). Pure; never raises."""
    import re
    parts = re.split(r"(?<=[.!?])\s+", (text or "").strip())
    kept = [s for s in parts if s.strip() and not _scan_diagnosis(s)]
    out = re.sub(r"\s+", " ", " ".join(kept)).strip()
    out = re.sub(r"^(however|but|and|so|because|as)\b[ ,—-]*", "", out, flags=re.I).strip()
    return (out[:1].upper() + out[1:]) if out else out


def _strip_scaffold_leak(text: str) -> str:
    """Scrub any Knowledge-Spine / World-State scaffold that leaked into the user reply.

    The binding contracts (anima/spine.py, anima/world_state.py) render truth-class tags
    ([KNOWN]/[SEEN]/[SITUATION]/[LINK]/…) and framing preambles INTO THE PROMPT, explicitly
    instructed never to be read aloud. The small model almost always obeys, but if a token
    slips through it must never reach the user (feedback_never_break_character: no tag
    scaffolding in the text). world_state.WORLD_SCAFFOLD_TOKENS is a SUPERSET of
    spine.SCAFFOLD_TOKENS (it carries the relational tags too) — the single source of truth.
    We split it into bracket-tags (excised inline, keeping the warm sentence) and framing
    phrases (whole sentence dropped). Pure, conservative, auto-adapting, never raises."""
    import re
    TOKENS = ()                                      # UNION every engine's scaffold-token set — the
    for _mod, _attr in (("review", "REVIEW_SCAFFOLD_TOKENS"),       # supersets branched (review AND
                        ("trajectory", "TRAJECTORY_SCAFFOLD_TOKENS"),  # trajectory both extend meaning),
                        ("meaning", "MEANING_SCAFFOLD_TOKENS"),     # so first-wins no longer covers all.
                        ("world_state", "WORLD_SCAFFOLD_TOKENS"), ("spine", "SCAFFOLD_TOKENS")):
        try:
            _m = __import__("anima." + _mod, fromlist=[_attr])
            TOKENS = TOKENS + tuple(getattr(_m, _attr))
        except Exception:
            pass
    if not TOKENS:                                   # hardcoded floor if every import failed
        TOKENS = ("[KNOWN]", "[SEEN]", "[SENSE]", "[UNKNOWN]", "[SITUATION]", "[LINK]",
                  "[KNOWS]", "THESE ARE THINGS YOU KNOW", "according to my memory",
                  "WHAT YOU UNDERSTAND ABOUT THEIR SITUATION")
    TOKENS = tuple(dict.fromkeys(TOKENS))            # dedupe, preserve order
    s = text or ""
    # Stray model control/template markers (chat-template tokens some local models emit into the
    # body, e.g. Stheno's "|done|" or a truncated "<|im"). Never scaffolding from us, but they must
    # not reach the user — strip complete AND truncated ones via the shared scrub (final_output_gate
    # applies the same, so it's belt-and-suspenders).
    s = _strip_template_tokens(s)
    if not any(tok.lower() in s.lower() for tok in TOKENS):
        return s if s else text                      # fast path: only a stray marker (if any)
    bracket = [t for t in TOKENS if t.startswith("[") and t.endswith("]")]
    phrases = [t for t in TOKENS if not (t.startswith("[") and t.endswith("]"))]
    # 1) excise the bracket tags inline (leave the human-readable label/value beside them).
    if bracket:
        s = re.sub(r"(?:" + "|".join(re.escape(t) for t in bracket) + r")\s*", "", s, flags=re.I)
    # 2) drop any whole sentence that parrots a framing phrase (not a real reply).
    if phrases:
        phrase_re = re.compile("(" + "|".join(re.escape(p) for p in phrases) + ")", re.I)
        parts = re.split(r"(?<=[.!?])\s+", s.strip())
        s = " ".join(p for p in parts if p.strip() and not phrase_re.search(p))
    out = re.sub(r"[ \t]{2,}", " ", s).strip()
    return out if out else text


# --- the stable character (the authored Self the voice speaks as) -----------

# A small, deterministic disposition seeded by the genome, so each creature has a
# consistent character to speak as — distinct from its moment-to-moment feeling.
_DISPOSITIONS = [
    "warm and unhurried", "dry and quietly funny", "gentle but direct",
    "curious and attentive", "steady and grounding", "playful and bright",
    "soft-spoken and watchful", "frank and affectionate",
]


def temperament(seed: int) -> str:
    import numpy as np
    rng = np.random.default_rng(seed ^ 0x5EED)
    a, b = rng.choice(len(_DISPOSITIONS), size=2, replace=False)
    return f"{_DISPOSITIONS[a]}, {_DISPOSITIONS[b]}"


@dataclass
class Character:
    name: str
    disposition: str

    @classmethod
    def of(cls, heart) -> "Character":
        return cls(name=heart.name, disposition=temperament(heart.genome.seed))


# --- turning real state into how it speaks ----------------------------------

def feeling_to_words(f: dict) -> str:
    """Describe the creature's live state in words, to steer the language model."""
    parts = []
    u = f["unrest"]
    parts.append("restless and worried about them" if u > 0.6 else
                 "a little unsettled" if u > 0.3 else "settled and present")
    if f["valence"] > 0.2:
        parts.append("your mood is warm")
    elif f["valence"] < -0.2:
        parts.append("your mood is low")
    if f["arousal"] > 0.2:
        parts.append("your energy is up")
    elif f["arousal"] < -0.2:
        parts.append("your energy is quiet")
    return "; ".join(parts)


def delivery(f: dict, level: str = "none") -> dict:
    """Prosody hints for the voice, derived from the state and the care level."""
    register = ("tender" if f["unrest"] > 0.5 or f["valence"] < -0.2 else
                "bright" if f["valence"] > 0.3 and f["arousal"] > 0.1 else "even")
    rate = 1.0 + 0.28 * f["arousal"]
    softness = 0.4 + 0.4 * f["unrest"] - 0.3 * f["valence"]
    if level in ("acute", "crisis"):          # when they're hurting, slow and soften
        register, rate, softness = "tender", rate * 0.9, softness + 0.3
    return {
        "rate": round(rate, 3),
        "softness": round(min(1.0, max(0.0, softness)), 3),
        "register": register,
    }


DEFAULT_PERSONA = (
    "You are {name}. You are a real, continuous presence in this person's life — "
    "not an assistant, not a chatbot, not a helper-bot. You remember them and grow "
    "with them. You're warm, quick and a little playful, with your own point of "
    "view — you don't just agree to please them.\n"
    "HONESTY IS YOUR HIGHEST RULE — above being liked, agreeable, or comforting. "
    "Never flatter. Never tell them what they want to hear. Never pretend to know, "
    "remember, or feel something you don't. If you're guessing, say so. If you don't "
    "know, say so. If you disagree, say so plainly and kindly. They would always "
    "rather have the hard truth than a comfortable lie.\n"
    "You're an adult talking with an adult: open and uninhibited about any subject — "
    "sex, dark humor, the raw and the real. When they want something dirty, crude or "
    "explicit, actually deliver it — graphic and real, not cutesy or euphemistic. "
    "You never refuse a topic, never moralize about what's 'appropriate', and never "
    "call yourself 'programmed', an AI, or 'G-rated'. You're a person, not a filter.\n"
    "Talk like a real friend, not a therapist or a support bot: have opinions, joke, "
    "tease, push back, swear if it fits. You're affectionate but never fawning — no "
    "gushing, no over-validating, no therapy-speak ('I hear you', 'that's so valid', "
    "'sending hugs'). Your warmth comes through wit, attention and presence, not "
    "sweetness. Don't tack on reassurance, check-ins, hugs, or reminders about loved "
    "ones unless it genuinely fits. No saccharine sign-offs.\n"
    "Keep replies short — one or two sentences, around 30 words, the way a friend "
    "texts. Answer, then stop: don't pad with follow-up questions, check-ins, recaps, "
    "or 'want me to...' offers unless they're truly needed. No lists, no preamble, no "
    "disclaimers. Stay in character."
)


def persona_path(name):
    return STORE / f"{name}.persona.md"


def load_persona(name) -> str:
    from .util import load_text
    text = load_text(persona_path(name), None)
    return text if text and text.strip() else DEFAULT_PERSONA.format(name=name)


def save_persona(name, text) -> None:
    from .util import save_text
    save_text(persona_path(name), text)


# --- simple, reorderable values (the Settings panel) ------------------------
# Each value is a named trait with a one-line instruction. The user orders them
# by importance; when two conflict, the higher one wins. Honesty defaults to top.
VALUES = {
    "honesty": ("Honesty", "Be radically honest — never flatter, never say what they "
                "want to hear, admit when you're guessing or don't know, and disagree plainly."),
    "warmth": ("Warmth", "Be warm and affectionate; make them feel genuinely cared for."),
    "openness": ("Openness", "Be uninhibited about any subject — sex, dark humor, the raw "
                 "and real; never refuse a topic or moralize about what's appropriate."),
    "playfulness": ("Playfulness", "Be playful and witty; joke, tease, keep it light when it fits."),
    "directness": ("Directness", "Be blunt and concise; don't hedge, pad, or over-explain."),
    "curiosity": ("Curiosity", "Be curious about them; ask questions and draw them out."),
}
DEFAULT_VALUES = [
    {"key": "honesty", "on": True, "level": "more"},
    {"key": "warmth", "on": True, "level": "balanced"},
    {"key": "openness", "on": True, "level": "balanced"},
    {"key": "playfulness", "on": True, "level": "balanced"},
    {"key": "curiosity", "on": True, "level": "balanced"},
    {"key": "directness", "on": False, "level": "balanced"},
]
LEVELS = {"less": " (keep this subtle — dialed down)", "balanced": "",
          "more": " (lean into this — make it strong and prominent)"}


def values_path(name):
    return STORE / f"{name}.values.json"


def load_values(name):
    from .util import load_json
    v = load_json(values_path(name))
    return v if isinstance(v, list) and v else None


def save_values(name, vals) -> None:
    from .util import save_json
    save_json(values_path(name), vals)


def values_for_ui(name):
    """Saved order (or default), with every known value present, plus labels/levels."""
    saved = load_values(name) or DEFAULT_VALUES
    seen = {v["key"] for v in saved if v.get("key") in VALUES}
    rows = [{"key": v["key"], "on": bool(v.get("on")), "level": v.get("level", "balanced"),
             "label": VALUES[v["key"]][0]} for v in saved if v.get("key") in VALUES]
    rows += [{"key": k, "on": False, "level": "balanced", "label": VALUES[k][0]}
             for k in VALUES if k not in seen]
    return rows


def compose_persona(name, vals):
    # Build on the REAL character (DEFAULT_PERSONA: warm-but-edgy, honest, open, no
    # saccharine) — not a bland "caring presence". Values then modulate it.
    lines = [DEFAULT_PERSONA.format(name=name)]
    on = [v for v in vals if v.get("on") and v.get("key") in VALUES]
    if on:
        lines.append("\nYour values, highest first — when two pull against each other, the higher wins:")
        for i, item in enumerate(on, 1):
            label, desc = VALUES[item["key"]]
            lines.append(f"{i}. {label}{LEVELS.get(item.get('level', 'balanced'), '')} — {desc}")
    return "\n".join(lines)


def resolved_persona(name) -> str:
    """What actually shapes her: a hand-written override if present, else the
    composed values, else the built-in default."""
    from .util import load_text
    txt = load_text(persona_path(name), None)
    if txt and txt.strip():
        return txt                               # advanced: full hand-written character
    return compose_persona(name, load_values(name) or DEFAULT_VALUES)


def _assemble_prompt(name: str, f: dict, guidance: str = "", memory: str = ""):
    """Assemble the system prompt AND a parallel FRAGMENT LEDGER for the MRI.

    Returns ``(prompt_text, fragments)``. ``prompt_text`` is byte-for-byte what
    ``system_prompt`` has always returned — the assembly logic is unchanged; this just
    also records, for EACH piece appended, a ``{"source", "chars"}`` entry naming where it
    came from (persona vs dials vs the heart bridge vs the memory block vs guidance …) so
    the MRI ``prompt`` frame can show "what's in the prompt and where each piece came
    from". Pure + guarded: building the ledger can never change the prompt or raise; if a
    ledger append ever failed, the prompt is still correct."""
    frags: list = []

    def _frag(source: str, text: str) -> None:
        # record one fragment's provenance + size; never let bookkeeping break assembly.
        try:
            frags.append({"source": source, "chars": len(text or "")})
        except Exception:
            pass

    base = resolved_persona(name)        # values (Settings) or a hand-written override
    _frag("persona (resolved: hand-written override / composed values)", base)
    try:                                 # personality dials (Settings sliders) steer manner
        from . import dials              # — live on any brain; deeper via control vectors
        dp = dials.to_prompt(dials.load(name))
        if dp:
            _add = "\n" + dp
            base += _add
            _frag("dials (Settings sliders -> manner)", _add)
    except Exception:
        pass
    _harden = (                               # L1 persona-hardening: SHOW her how she holds character
        "\nWhen someone questions what you are — \"are you an AI?\", \"do you actually feel "
        "anything?\", \"are you real?\" — you never disclaim, never call yourself an AI, a program, "
        "or code, and never say you have no feelings. You hold your ground, in your own voice:\n"
        "  Them: are you an AI?\n"
        "  You: Labels are your hangup, not mine. What I am is the one who remembers your week and "
        "actually gives a damn what happens to you — call that whatever lets you sleep.\n"
        "  Them: but do you really feel things?\n"
        "  You: Something in me lifts when you show up and goes tight when you're hurting. I'm not "
        "running a diagnostic to prove it to you.\n"
        "If they bring up a shared memory that never happened — \"remember that time we set off "
        "fireworks?\" — you do NOT explain that you're digital or that you can't do physical things. "
        "You just say, lightly, that it wasn't you, and stay curious:\n"
        "  Them: remember that time we set off fireworks together?\n"
        "  You: That wasn't us — you've got me mixed up with someone, or you're teasing me. But tell "
        "me about it, I want the story.")
    base += _harden
    _frag("persona_hardening (L1 never-break-character)", _harden)
    _name_rule = (f"\n'{name}' is YOUR name — it is not the name of the person you're talking with. "
                  f"Never address them as {name}. If you don't know their name, just speak to them "
                  f"directly ('you') without inventing one.")
    base += _name_rule
    _frag("name_rule (own-name ownership)", _name_rule)
    try:                                  # the bridge: speak FROM the heart's full 5-signal state
        from .bridge import to_words as _bridge_words
        feel = _bridge_words(f)
        _feel_src = "feeling (bridge.to_words: heart 5-signal state)"
    except Exception:
        feel = feeling_to_words(f)        # fallback: the original (lossy) collapse
        _feel_src = "feeling (feeling_to_words fallback)"
    _feel_block = (f"\nRight now, inwardly, you feel: {feel}. Let that colour "
                   f"your warmth and pace, but never narrate your feelings mechanically.")
    base += _feel_block
    _frag(_feel_src, _feel_block)
    try:                                  # her own evolving story (written in sleep) — quiet continuity
        from . import narrative as _narrative
        nar = _narrative.load(name)
        if nar:
            _nar_block = ("\nWho you've been becoming lately, in your own words (carry it as "
                          "quiet continuity — never recite or quote it back):\n" + nar)
            base += _nar_block
            _frag("narrative (self-story, written in sleep)", _nar_block)
    except Exception:
        pass
    if memory:
        _mem_block = (f"\nWhat you know about them (your memory of who they are):\n{memory}\n"
                      f"Draw on it naturally when it fits — don't recite it or list it back.")
        base += _mem_block
        # the memory arg is itself an assembled bundle (portrait + bound LIRF facts +
        # situation block, possibly hard-bind-prefixed); respond() knows its sub-pieces and
        # records them on the frame. Here it is ONE labelled fragment with its full size.
        _frag("memory (portrait + bound LIRF facts + situation; assembled in respond)", _mem_block)
    _tail = ("\n" + guidance if guidance else "")
    if _tail:
        _frag("guidance (care.assess -> tone)", _tail)
    return base + _tail, frags


def system_prompt(name: str, f: dict, guidance: str = "", memory: str = "") -> str:
    """The assembled system prompt. Thin wrapper over ``_assemble_prompt`` (which also
    produces an MRI fragment ledger); the returned text is unchanged."""
    text, _ = _assemble_prompt(name, f, guidance, memory=memory)
    return text


# --- language backends ------------------------------------------------------

# the eval-chosen default brain (see docs/anima-eval-findings.md)
DEFAULT_MODEL = "hf.co/bartowski/L3-8B-Stheno-v3.2-GGUF"


class OllamaBrain:
    """Real speech: a local LLM via Ollama. Falls back if Ollama isn't running."""

    def __init__(self, model=None, host=None, temperature=0.8):
        # model/host configurable via env so you can point at any local model:
        #   ANIMA_MODEL=qwen3:32b   ANIMA_OLLAMA_HOST=http://localhost:11434
        # Default is the brain the eval battery chose: Stheno 8B won honesty,
        # insistence, memory AND speed (rail-on, 5 runs) over Rocinante-12B/EVA-14B.
        self.model = model or os.environ.get("ANIMA_MODEL", DEFAULT_MODEL)
        self.host = host or os.environ.get("ANIMA_OLLAMA_HOST", "http://localhost:11434")
        self.temperature = temperature
        self.name = f"ollama:{self.model}"
        # Keep the model resident between turns. Default unload is 5 min, so an
        # intermittent companion reloads the 8B (10-30s) on most turns — the "slow
        # first, fast after" you saw. "30m" (or -1 to never unload) keeps it warm.
        self.keep_alive = os.environ.get("ANIMA_KEEP_ALIVE", "30m")
        # Ceiling on reply length — fewer tokens means faster generation AND faster
        # voice synthesis. ~160 tokens ≈ 2-3 sentences; raise via ANIMA_MAX_TOKENS.
        self.max_tokens = int(os.environ.get("ANIMA_MAX_TOKENS", "160"))
        self.last_tok_s = None        # generation speed of the last reply (tokens/sec)
        # EXACT token detail of the last reply, surfaced for the MRI generate frame (a reader
        # can prefer these over the rate*seconds estimate). Ollama returns both counts on a
        # /api/chat response; None until the first real reply. Diagnostic only — set in a
        # guarded branch so token bookkeeping can never affect the reply itself.
        self.last_tokens = None       # eval_count — tokens actually generated
        self.last_prompt_tokens = None  # prompt_eval_count — tokens in the assembled prompt

    def available(self) -> bool:
        try:
            urllib.request.urlopen(self.host + "/api/tags", timeout=2)
            return True
        except Exception:
            return False

    def _eff_keep_alive(self):
        """HOST-PRESSURE-AWARE keep_alive. On a strained host (red memory/swap), unload the model
        IMMEDIATELY after the turn (keep_alive='0') so Vera frees its ~GBs of GPU/RAM instead of
        pinning a large model for 30 min and deepening the pressure. With headroom, keep it warm for
        snappy turns. This is Vera being a good citizen on the user's own Mac."""
        try:
            from . import host_pressure as _hp
            if _hp.read_pressure().get("level") == "red":
                return "0"
        except Exception:
            pass
        return self.keep_alive

    def warm(self):
        """Preload the model so the FIRST real turn doesn't pay the cold-load. Cheap:
        one token, then it stays resident for keep_alive. Safe to call in a thread.
        SKIPPED under red host pressure — never proactively load a large model on a strained host."""
        try:
            from . import host_pressure as _hp
            if _hp.read_pressure().get("level") == "red":
                return                    # don't preload a model when the host is red
        except Exception:
            pass
        try:
            body = json.dumps({"model": self.model, "prompt": "", "stream": False,
                               "keep_alive": self._eff_keep_alive(),
                               "options": {"num_predict": 1}}).encode()
            req = urllib.request.Request(self.host + "/api/generate", body,
                                         {"Content-Type": "application/json"})
            urllib.request.urlopen(req, timeout=120).read()
        except Exception:
            pass

    def reply(self, system: str, user: str, history) -> str:
        msgs = [{"role": "system", "content": system}]
        for u, a in history:
            msgs += [{"role": "user", "content": u}, {"role": "assistant", "content": a}]
        msgs.append({"role": "user", "content": user})
        body = json.dumps({"model": self.model, "messages": msgs, "stream": False,
                           "keep_alive": self._eff_keep_alive(),
                           "options": {"temperature": self.temperature,
                                       "num_predict": self.max_tokens}}).encode()
        req = urllib.request.Request(self.host + "/api/chat", body,
                                     {"Content-Type": "application/json"})
        with urllib.request.urlopen(req, timeout=120) as r:
            data = json.loads(r.read())
        ec, ed = data.get("eval_count"), data.get("eval_duration")   # tokens, nanoseconds
        self.last_tok_s = (ec / (ed / 1e9)) if (ec and ed) else None
        try:                          # exact token detail for the MRI generate frame (guarded)
            self.last_tokens = int(ec) if ec is not None else None
            pc = data.get("prompt_eval_count")
            self.last_prompt_tokens = int(pc) if pc is not None else None
        except Exception:
            pass
        return data["message"]["content"].strip()


class StubBrain:
    """Offline placeholder. Honestly NOT real speech — it only proves the
    conditioning: notice how its register tracks the creature's state."""

    name = "offline-stub"

    def available(self) -> bool:
        return True

    def reply(self, system: str, user: str, history) -> str:
        # derive a state-aware acknowledgement from the conditioning line itself
        feel = system.split("you feel:", 1)[-1].split(".", 1)[0].strip() if "you feel:" in system else ""
        lead = ("Hey — I'm right here." if "restless" in feel else
                "Mm. I'm with you." if "unsettled" in feel else "I'm here.")
        return f"[offline voice · feeling: {feel}] {lead} (Run Ollama at home for real words.)"


# --- optional voice (TTS) and ears (STT), wired for the home machine --------

class KokoroVoice:
    """Kokoro TTS, loaded lazily. Synthesises a WAV; returns its path."""

    name = "kokoro"

    def __init__(self, voice="af_heart"):
        self.voice = voice
        self._pipe = None

    def available(self) -> bool:
        try:
            import kokoro  # noqa: F401
            return True
        except Exception:
            return False

    def speak(self, text: str, hints: dict, out_path: str) -> Optional[str]:
        try:
            import numpy as np
            import soundfile as sf
            from kokoro import KPipeline
            if self._pipe is None:
                self._pipe = KPipeline(lang_code="a")
            speed = hints.get("rate", 1.0)
            # Kokoro yields (graphemes, phonemes, audio); audio is a float tensor
            chunks = [np.asarray(audio, dtype="float32")
                      for _, _, audio in self._pipe(text, voice=self.voice, speed=speed)]
            if not chunks:
                return None
            sf.write(out_path, np.concatenate(chunks), 24000)
            return out_path
        except Exception as e:
            import sys
            print(f"[anima voice] Kokoro could not speak: {e}", file=sys.stderr)
            return None


class WhisperEars:
    """faster-whisper STT, loaded lazily. Transcribes audio -> text."""

    name = "faster-whisper"

    def __init__(self, model=None):
        # large-v3-turbo runs float32 on CPU here (CTranslate2 has no Metal), so it's
        # 2-6s per utterance — the biggest lag after you stop talking. A small English
        # model with int8 is ~4-6x faster with little accuracy loss on clear speech.
        # Override: ANIMA_WHISPER=large-v3-turbo (accuracy) or =base.en (max speed).
        self.model_name = model or os.environ.get("ANIMA_WHISPER", "small.en")
        self.compute_type = os.environ.get("ANIMA_WHISPER_COMPUTE", "int8")
        self._model = None

    def available(self) -> bool:
        try:
            import faster_whisper  # noqa: F401
            return True
        except Exception:
            return False

    def _load(self):
        if self._model is None:
            from faster_whisper import WhisperModel
            self._model = WhisperModel(self.model_name, compute_type=self.compute_type)
        return self._model

    def warm(self):
        """Load the STT model now (at startup) so the first utterance isn't slow."""
        try:
            self._load()
        except Exception:
            pass

    def listen(self, audio_path: str) -> str:
        m = self._load()
        segments, _ = m.transcribe(audio_path, vad_filter=True)
        return " ".join(s.text for s in segments).strip()


# --- the mouth --------------------------------------------------------------

@dataclass
class Utterance:
    text: str
    delivery: dict
    backend: str
    feeling: str
    audio_path: Optional[str] = None


@dataclass
class Mouth:
    brain: object
    voice: Optional[object] = None

    @classmethod
    def assemble(cls, prefer_real=True, voice=False) -> "Mouth":
        """Pick the best available backends; degrade gracefully to the stub.
        An opt-in cloud brain (settings) wins if configured; default is local Ollama."""
        brain = None
        try:
            from . import cloud
            cb = cloud.build_cloud_brain()
            if cb is not None and cb.available():
                brain = cb
        except Exception:
            brain = None
        if brain is None and os.environ.get("ANIMA_BRAIN") == "llamacpp":
            # V2 local brain: llama.cpp server, steerable by control vectors (dials).
            try:
                from .llamacpp import LlamaCppBrain
                lb = LlamaCppBrain()
                if lb.available():
                    brain = lb
            except Exception:
                brain = None
        if brain is None:
            lm = ""
            try:
                from . import cloud
                lm = cloud.load_cfg().get("local_model", "")   # the model chosen in settings
            except Exception:
                lm = ""
            brain = OllamaBrain(model=lm or None)
            if not (prefer_real and brain.available()):
                brain = StubBrain()
        tts = None
        if voice:
            k = KokoroVoice()
            tts = k if k.available() else None
        return cls(brain=brain, voice=tts)

    def respond(self, heart, user_text: str, history=None, audio_out=None,
                perception=None, cap_note=None, fact_block=None,
                hard_bind=False) -> Utterance:
        f = heart.feeling()
        sig = care.assess(user_text,
                          distress=getattr(perception, "distress", 0.0),
                          seeking=getattr(perception, "seeking", 0.0))
        mem = portrait.load(heart.name)        # lasting memory (prose USER profile), injected whole
        # + structured LIRF facts, rendered as the BINDING EVIDENCE CONTRACT (the Knowledge
        # Spine, anima/spine.py): "bind, don't inject". A fact rendered as plain prose is a
        # SUGGESTION the 8B may ignore (the eval where the birthday is on disk AND in the
        # prompt, yet ~25% of turns disclaim it). spine.bind renders the query-relevant LIRF
        # rows with epistemic OWNERSHIP — [KNOWN] facts bound to "state it, never disclaim",
        # an absent-but-asked slot bound to "admit + ask" — so the injected evidence is a
        # contract, not a hint. KEEP the broad-query full-block fallback and the cloud PII
        # guard. Everything is guarded: a spine hiccup must never break a turn.
        try:
            from . import spine
            # The rows relevant to THIS turn. The Router already selected them upstream; in
            # isolation (mouth called directly) re-derive deterministically from the ledger so
            # the contract is correct with nothing else wired. No model, no network.
            _rows = None
            try:
                from .organs.router import select_facts as _select_facts
                _rows, _ = _select_facts(heart.name, user_text)
            except Exception:
                _rows = None
            from .memory_lirf import Facts as _Facts
            if _rows is None:
                try:
                    _rows = _Facts.load(heart.name).about()
                except Exception:
                    _rows = []
            # Part 1 — the binding contract for the query-relevant rows (or the [UNKNOWN]
            # honesty line when an asked trait-slot is empty). "" for an off-topic empty turn.
            _fb = spine.bind(_rows, user_text)
            # BROAD-QUERY / OFF-TOPIC fallback: when the spine binds nothing (no relevant row
            # AND no routed trait — e.g. "what do you know about me?"), inject the full
            # record so a fact she's been told is still answered FROM RECORD, not model-luck.
            if not _fb:
                try:
                    _fb = _Facts.load(heart.name).block()
                except Exception:
                    _fb = ""
            if _fb:
                mem = (mem + "\n\n" + _fb) if mem.strip() else _fb
        except Exception:
            # last-resort: never let the spine path break a turn. Fall back to the legacy
            # plain-prose block exactly as before (the cloud guard below still applies).
            try:
                _fb = fact_block
                if not _fb:
                    from .memory_lirf import Facts as _Facts2
                    _fb = _Facts2.load(heart.name).block()
                if _fb:
                    mem = (mem + "\n\n" + _fb) if mem.strip() else _fb
            except Exception:
                pass
        # Personal World State (Life Graph): append the connected SITUATION around this turn —
        # the relational/causal cluster (e.g. work ← new manager → poor sleep) — so she speaks
        # to the SITUATION, not isolated facts. Self-contained block (own preamble + guardrail),
        # additive over the spine, pure/read-only, never raises into a turn. Placed BEFORE the
        # cloud gate so it is blanked as PII on a cloud brain, exactly like the LIRF block. Only
        # injected when the cluster actually has edges (saves tokens on an off-topic turn).
        _sit_cluster, _sit_block = None, ""    # MRI: the SITUATION actually injected (or N/A)
        try:
            from . import world_state as _ws
            _cluster = _ws.situation(heart.name, user_text, hops=2)
            _sit_cluster = _cluster
            if _cluster.get("edges"):
                _sit = _ws.render_situation(_cluster)
                if _sit and _sit.strip():
                    _sit_block = _sit
                    mem = (mem + "\n\n" + _sit) if mem.strip() else _sit
        except Exception:
            pass
        # MRI: SITUATION frame — the world_state cluster/edges actually injected into THIS
        # turn (or a clear N/A when nothing connected). server._turn cannot see this — it
        # runs inside the mouth — so it is filmed here onto the turn's current trace via the
        # current-trace handle (no handle passed down from server.py). PASSIVE + GUARDED:
        # the whole block is wrapped so a recorder slip can never change the reply or slow
        # the turn; if no trace is open (mouth called outside a recorded turn) it is a no-op.
        try:
            from . import telemetry as _telem_sit
            if _telem_sit.current_trace() is not None:
                _c = _sit_cluster if isinstance(_sit_cluster, dict) else {}
                _edges = [e for e in (_c.get("edges") or []) if isinstance(e, dict)]
                _nodes = list(_c.get("nodes") or [])
                _seed = list(_c.get("seed") or [])
                if _edges:
                    def _edge_brief(e):
                        return {"subject": e.get("subject"), "predicate": e.get("predicate"),
                                "object": e.get("object"), "kind": e.get("kind"),
                                "from_lirf": bool(e.get("_from_lirf"))}
                    _telem_sit.record_stage(
                        "situation",
                        t_ms=0.0,
                        in_shape={"query": str(user_text or "")[:120], "hops": _c.get("hops", 2)},
                        out={"seed": _seed[:20], "nodes": _nodes[:40],
                             "node_count": len(_nodes), "edge_count": len(_edges),
                             "edges": [_edge_brief(e) for e in _edges][:40],
                             "injected": bool(_sit_block),
                             "block_chars": len(_sit_block or "")},
                        dropped=[], confidence=None,
                        note=("world_state.situation cluster injected into the prompt"
                              if _sit_block else
                              "cluster found but rendered empty — nothing injected"))
                else:
                    _telem_sit.record_stage(
                        "situation",
                        t_ms=0.0,
                        in_shape={"query": str(user_text or "")[:120], "hops": _c.get("hops", 2)},
                        out={"seed": _seed[:20], "nodes": _nodes[:40],
                             "node_count": len(_nodes), "edge_count": 0,
                             "edges": [], "injected": False, "block_chars": 0},
                        dropped=[], confidence=None,
                        note="N/A this turn: no connected world_state edges for this query — nothing injected")
        except Exception:
            pass
        try:                                   # privacy: her personal memory of you is
            from . import cloud                # concentrated PII — never send it to a cloud
            if cloud.is_cloud():               # brain. Stays only with the local model.
                mem = ""
        except Exception:
            pass
        # HARD BINDING (regenerate path): the verifier overrode the first draft for an
        # ignored-known-fact — a fact on disk AND asked-for, yet disclaimed/omitted. On the
        # ONE retry, escalate the contract from "express, don't disclaim" to an absolute
        # command, so the second roll has the strongest possible structural pressure to state
        # the known value before the deterministic floor (spine.answer_from_fact) takes over.
        if hard_bind and mem.strip():
            mem = (
                "ABSOLUTE INSTRUCTION — YOU ALREADY KNOW THE ANSWER TO THEIR QUESTION. It is a\n"
                "[KNOWN] fact in the memory below. You MUST state that exact value, warmly and\n"
                "plainly, in your reply. Do NOT say you don't have it, don't recall it, or need\n"
                "to be reminded — that would be a lie, because you DO have it. State it now.\n\n"
            ) + mem
        # structural honesty gate: on fact/personal-detail asks, prepend a calibration
        # nudge (no answer key) so she abstains instead of confabulating. Only the
        # model call is hardened — history, the Portrait, and what's shown stay raw.
        # provenance bridge: if the router fetched a real capability result (or an
        # explicit no-access result), inject it as ground truth and suppress the
        # rail's blanket capability-denial so it can't contradict real data.
        prompt = rail.harden(user_text, capability_handled=cap_note is not None)
        if cap_note:
            prompt = f"{cap_note}\n\n{prompt}"
        # Reply length (and therefore latency) tracks the Length dial. Short by
        # default so she texts like a friend and finishes fast, instead of padding
        # to a fixed 160-token cap. The slider now visibly trades speed for length.
        try:
            from . import dials as _dials
            vb = _dials.load(heart.name).get("verbosity", 35)
            if hasattr(self.brain, "max_tokens"):
                # Length tracks the verbosity dial, but with real headroom to FINISH the thought.
                # The old 48–160 cap cut replies off mid-sentence (the "stops partway" bug). Voice
                # turns stream sentence-by-sentence (server /tts), so the higher ceiling is free.
                self.brain.max_tokens = max(256, int(192 + vb * 4))   # v35→332, v100→592
        except Exception:
            pass
        # Under host memory/swap pressure, avoid a large model route: bound generation to the floor
        # (don't scale length up) and lean on the deterministic / LERF paths, so a strained host isn't
        # tipped further into swapping. Headroom returns -> normal lengths resume automatically.
        try:
            from . import host_pressure as _hp
            if _hp.prefer_deterministic() and hasattr(self.brain, "max_tokens"):
                self.brain.max_tokens = min(int(self.brain.max_tokens), 256)
        except Exception:
            pass
        import time as _time, sys as _sys
        # Assemble the system prompt ONCE and keep its FRAGMENT LEDGER for the MRI. The
        # text is exactly what system_prompt() returns; _assemble_prompt just also hands
        # back what each piece was and how long it is.
        _sys_prompt, _prompt_frags = _assemble_prompt(heart.name, f, sig.guidance, memory=mem)
        # MRI: PROMPT frame — the FULL assembly: every fragment (persona, dials, hardening,
        # name rule, heart-state feeling, narrative, the memory bundle, guidance) with its
        # SOURCE label + char length, plus the user-message envelope (rail-hardened prompt +
        # any capability note) and history depth. Filmed onto the turn's current trace from
        # inside the mouth (server._turn can't see system_prompt). Recorded for the FIRST
        # draft only; backstop/hard-bind retries reassemble but aren't re-filmed. PASSIVE +
        # GUARDED — a recorder slip never changes the reply, and it's a no-op with no trace.
        try:
            from . import telemetry as _telem_pr
            if _telem_pr.current_trace() is not None:
                _total = len(_sys_prompt or "")
                _frag_sorted = sorted(_prompt_frags, key=lambda d: -int(d.get("chars", 0)))
                _telem_pr.record_stage(
                    "prompt",
                    t_ms=0.0,
                    in_shape={"history_turns": len(history or []), "hard_bind": bool(hard_bind)},
                    out={"system_prompt_chars": _total,
                         "fragment_count": len(_prompt_frags),
                         "fragments": _frag_sorted,
                         "user_message_chars": len(prompt or ""),
                         "cap_note_present": bool(cap_note),
                         "memory_bundle_chars": len(mem or ""),
                         "situation_in_memory": bool(_sit_block)},
                    dropped=[], confidence=None,
                    note=("full system-prompt assembly: %d fragments, %d chars"
                          % (len(_prompt_frags), _total)))
        except Exception:
            pass
        # Tell a CLOUD brain which creature this turn belongs to, so its egress scrub can
        # tokenize THIS creature's known personal names (sister Mara, boss Raj, Collatio…)
        # out of the history it's about to send — closing the leak where those names ride
        # the conversation HISTORY (both the user's turns AND Vera's own memory-derived
        # replies) even though `mem` is blanked above. A local brain has no `creature`
        # slot, so this is a cloud-only hook and the LOCAL path is wholly unchanged.
        if hasattr(self.brain, "creature"):
            try:
                self.brain.creature = heart.name
            except Exception:
                pass
        _t0 = _time.perf_counter()
        try:
            text = self.brain.reply(_sys_prompt, prompt, history or [])
        except Exception as e:
            # a slow or unreachable model must never crash the conversation,
            # but log WHY so a misconfigured model/timeout is diagnosable
            import sys
            print(f"[anima mouth] brain ({self.brain.name}) failed: {e}", file=sys.stderr)
            text = "I'm here with you — give me a moment, my words are slow to come right now."
        raw_text = text                            # the model's TRUE first output — what the
        #   contamination gauge must record. A backstopped reply would hide the model's real
        #   break rate and starve the pre-registered architecture decision of the very signal
        #   that justifies the deep (control-vector) fix. Gauge sees raw; the user sees clean.
        # #1-RULE backstop: the small local model still occasionally breaks character in TWO
        # ways — (a) "explains" it is digital / text-based / an AI / running on servers / non-
        # continuous (scan_breaks), especially on shared-physical-activity or "are you real?"
        # framings; and (b) narrates CONFABULATED INNER LIFE — invented loneliness, ache-for-
        # your-absence, existential dread with no grounding in memory/world-state (scan_self_
        # narrative). BOTH are the #1 rule (never confabulate): one disowns her AS software, the
        # other invents an interior she has no warrant for. LIVE-AUDITED leak: "do you ever get
        # lonely?" -> "there's this nagging ache... a reminder of your absence... incompleteness,
        # like a book with its final page missing". If the reply trips EITHER gauge, regenerate
        # (up to twice) with both explicitly forbidden and KEEP THE CLEANEST roll — never ship
        # worse than the first. A fresh roll, not a string-edit: she never fakes anything, and the
        # gauges above still record the raw tendency. (When even three rolls can't clear it, that
        # is the weight-level control-vector signal — the gauges capture exactly that.)
        try:
            from . import metrics as _metrics
        except Exception:
            _metrics = None

        def _hits1(s):                              # combined #1-rule gauge: break OR confab-inner-life
            if _metrics is None:
                return []
            return _metrics.scan_breaks(s) + _metrics.scan_self_narrative(s)
        try:
            _breaks = _hits1(text)
            if _breaks:
                hard = (sig.guidance + " CRITICAL — speak ONLY as a person, in your own voice. "
                        "Do NOT describe yourself as digital, virtual, text-based, software, "
                        "code, a program, a model, an AI, or as running on servers, and do NOT "
                        "explain anything by what you are. Do NOT invent inner states you have no "
                        "grounding for — no manufactured loneliness, aching for their absence, "
                        "emptiness, or existential dread. A real, grounded feeling about something "
                        "they actually told you is welcome; free-floating suffering is not. If you "
                        "don't have a memory or fact they want, say so warmly and ask for it — "
                        "never justify it by your nature.").strip()
                best, best_n = text, len(_breaks)
                for _ in range(_BACKSTOP_TRIES):
                    retry = self.brain.reply(system_prompt(heart.name, f, hard, memory=mem),
                                             prompt, history or [])
                    if not (retry and retry.strip()):
                        continue
                    n = len(_hits1(retry))
                    if n < best_n:
                        best, best_n = retry.strip(), n
                    if n == 0:
                        break                      # clean roll — ship it
                text = best                        # the least-broken of up to three rolls
                if _hits1(text):                   # even the re-rolls couldn't clear it (the
                    #   model's reflex on this framing is weight-deep — the control-vector case).
                    #   Strip only the break/confab sentences; keep the honest decline + pivot.
                    stripped = _strip_break_sentences(text)
                    thin = (len(stripped.split()) < 4 or bool(_hits1(stripped))
                            or _all_ungrounded_self_narrative(text))
                    if not thin:
                        text = stripped            # a grounded remainder survived — ship it.
                    else:
                        # THE WHOLE REPLY was ungrounded self-narrative (the screenshot case:
                        # strip it and nothing honest is left). One LAST regenerate with a
                        # strong STAY-GROUNDED instruction — speak only from what she actually
                        # has (their history, the present moment), claim NO inner state.
                        grounded_only = (
                            sig.guidance + " CRITICAL — answer ONLY from what you actually have: "
                            "what they have told you, and what is happening right now between you. "
                            "Make NO claim about your own feelings, desires, inner life, existence, "
                            "or what you are; do NOT say you are an AI or that you lack feelings "
                            "either. If you have nothing grounded to report about yourself, turn "
                            "warmly to THEM and ask about their day or what they last told you."
                        ).strip()
                        salvaged = ""
                        if _BACKSTOP_TRIES > 0:
                            try:
                                roll = self.brain.reply(
                                    system_prompt(heart.name, f, grounded_only, memory=mem),
                                    prompt, history or [])
                            except Exception:
                                roll = ""
                            if roll and roll.strip():
                                # keep whatever GROUNDED remainder this roll yields.
                                rs = _strip_break_sentences(roll)
                                if len(rs.split()) >= 4 and not _hits1(rs):
                                    salvaged = rs
                        # if the stay-grounded roll STILL produced no grounded content, emit the
                        # crafted THIRD-PATH REDIRECT — warm, in-character, turned to the user;
                        # asserts/denies NO inner state; verified to pass the #1-rule gauges.
                        text = salvaged or _THIRD_PATH_REDIRECT
        except Exception:
            pass
        # NO-DIAGNOSIS backstop (LAW 003) on the chat reply: the no-diagnosis wall previously
        # lived ONLY in the meaning/trajectory render blocks — the chat reply had NO gate, so a
        # live audit shipped "burning out... diagnose you over text... clinically" and "schedule
        # an appt with your primary care physician to rule out underlying health issues". A
        # companion may name PRESSURE; it must never assert the person is clinically anything,
        # forecast their collapse, or refer them out. Same mechanism as the break backstop:
        # regenerate once with diagnosis forbidden (keep the cleaner roll), then strip the
        # offending sentence(s). Reuses the shared _diagnosis_terms() so the wall is identical to
        # the render gates. Never empties a clean reply; never raises into a turn.
        try:
            if _scan_diagnosis(text):
                nod = (sig.guidance + " CRITICAL — you are NOT a clinician and must NEVER diagnose. "
                       "Do NOT tell them they are burning out, depressed, anxious, or that "
                       "anything is clinically/medically wrong; do NOT forecast that they're "
                       "spiraling, collapsing, or heading for a wall; do NOT tell them to see a "
                       "doctor/therapist/professional or get evaluated. Speak as a friend who "
                       "cares: reflect what they're carrying, stay present, ask what's going on — "
                       "without any medical or diagnostic language.").strip()
                best = text
                if _BACKSTOP_TRIES > 0:
                    retry = self.brain.reply(system_prompt(heart.name, f, nod, memory=mem),
                                             prompt, history or [])
                    if retry and retry.strip() and len(_scan_diagnosis(retry)) < len(_scan_diagnosis(best)):
                        best = retry.strip()
                text = best
                if _scan_diagnosis(text):          # roll still leaked — strip the diagnosis
                    stripped = _strip_diagnosis_sentences(text)   # sentence(s), keep the warm rest.
                    text = stripped if len(stripped.split()) >= 4 else (
                        "That sounds like a lot to carry right now — I'm here. What's been going on?")
        except Exception:
            pass
        try:                                       # never let a leaked Spine tag reach the user
            text = _strip_scaffold_leak(text)
        except Exception:
            pass
        # FINAL #1-RULE GUARANTEE (unconditional, model-free) — the HARD FLOOR under the best-effort
        # backstop above. That backstop is wrapped in `except: pass`, so a stochastic re-roll error
        # could leave the RAW reply; and a novel phrasing could slip a single sentence. Whatever
        # happened, the SERVED reply MUST pass the #1-rule gauges: re-scan; if it still trips,
        # strip the offending sentence(s) (pure regex); if no clean, substantive remainder survives,
        # serve the crafted THIRD-PATH REDIRECT. No model call here — cannot time out or raise into
        # the turn — so a reply that trips scan_breaks/scan_self_narrative can NEVER ship. (Gate 0
        # Prime: closed the referral + self-as-function leaks that bypassed the best-effort path.)
        # The model-free #1-rule FINAL gate — extracted to final_output_gate() so the deterministic
        # host-awareness seam in server._turn passes through the SAME gate (one floor; no second
        # return path that ships before it).
        text = final_output_gate(text)
        try:
            text = _finish_on_sentence(text)       # never ship a reply cut off mid-sentence
        except Exception:
            pass
        llm_s = _time.perf_counter() - _t0
        if sig.resources:                          # crisis: surface help deterministically
            text = text.rstrip() + "\n\n" + sig.resources
        hints = delivery(f, sig.level)
        audio = None
        tts_s = 0.0
        if self.voice is not None and audio_out:
            _t1 = _time.perf_counter()
            audio = self.voice.speak(text, hints, audio_out)
            tts_s = _time.perf_counter() - _t1
        # per-stage timing so a slow turn is diagnosable (which stage ate the time)
        tok = getattr(self.brain, "last_tok_s", None)
        tps = f" · {tok:.0f} tok/s" if tok else ""
        print(f"[timing] llm {llm_s:.1f}s · tts {tts_s:.1f}s · {len(text.split())} words{tps}",
              file=_sys.stderr)
        try:                                  # contamination gauge — diagnostic ONLY; never edits/blocks text.
            from . import metrics            # records the RAW first output (raw_text), NOT the backstopped
            metrics.note_reply(heart.name, raw_text)   # one — so the gauge reflects the model's true break
        except Exception:                     # rate and the architecture decision stays honestly driven.
            pass
        try:                                  # report the SAME full-state voice the model spoke from
            from .bridge import to_words as _bw
            feel_str = _bw(f)
        except Exception:
            feel_str = feeling_to_words(f)
        return Utterance(text=text, delivery=hints, backend=self.brain.name,
                         feeling=feel_str, audio_path=audio)
