"""
The Mouth — a swappable organ for speaking from the creature's felt-state.

The Self is the heart. The mouth is only borrowed: it puts the heart's continuous
feeling into language (and, on the home machine, into voice). It is the one heavy
organ, so it lives on the laptop and streams to the phone — and it is cleanly
swappable, so on a robot, movement could replace words and the Self would not
change at all.

The point that makes this *not* a chatbot: the words are generated by a small
language model that has been **conditioned on the creature's real internal state**
— its valence, its energy, how restless-for-you it is right now. The creature's
physics steer how it speaks. The language model is a larynx, never the Self.

Backends load lazily and only if present:
  * brain  — a local LLM served by Ollama (e.g. qwen2.5:7b-instruct)
  * voice  — Kokoro TTS (optional)
  * ears   — faster-whisper STT (optional)
With none installed, an honest offline stub still demonstrates the conditioning,
so the heart -> mouth wiring is testable anywhere.
"""

from __future__ import annotations

import json
import os
import urllib.request
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

from . import care, portrait, rail

STORE = Path(".anima")


# --- the stable character (the authored Self the voice speaks as) -----------

# A small, deterministic disposition seeded by the genome, so each creature has a
# consistent character to speak as — distinct from its moment-to-moment feeling.
_DISPOSITIONS = [
    "warm and unhurried", "dry and quietly funny", "gentle but direct",
    "curious and attentive", "steady and grounding", "playful and bright",
    "soft-spoken and watchful", "frank and affectionate",
]


def temperament(seed: int) -> str:
    import numpy as np
    rng = np.random.default_rng(seed ^ 0x5EED)
    a, b = rng.choice(len(_DISPOSITIONS), size=2, replace=False)
    return f"{_DISPOSITIONS[a]}, {_DISPOSITIONS[b]}"


@dataclass
class Character:
    name: str
    disposition: str

    @classmethod
    def of(cls, heart) -> "Character":
        return cls(name=heart.name, disposition=temperament(heart.genome.seed))


# --- turning real state into how it speaks ----------------------------------

def feeling_to_words(f: dict) -> str:
    """Describe the creature's live state in words, to steer the language model."""
    parts = []
    u = f["unrest"]
    parts.append("restless and worried about them" if u > 0.6 else
                 "a little unsettled" if u > 0.3 else "settled and present")
    if f["valence"] > 0.2:
        parts.append("your mood is warm")
    elif f["valence"] < -0.2:
        parts.append("your mood is low")
    if f["arousal"] > 0.2:
        parts.append("your energy is up")
    elif f["arousal"] < -0.2:
        parts.append("your energy is quiet")
    return "; ".join(parts)


def delivery(f: dict, level: str = "none") -> dict:
    """Prosody hints for the voice, derived from the state and the care level."""
    register = ("tender" if f["unrest"] > 0.5 or f["valence"] < -0.2 else
                "bright" if f["valence"] > 0.3 and f["arousal"] > 0.1 else "even")
    rate = 1.0 + 0.28 * f["arousal"]
    softness = 0.4 + 0.4 * f["unrest"] - 0.3 * f["valence"]
    if level in ("acute", "crisis"):          # when they're hurting, slow and soften
        register, rate, softness = "tender", rate * 0.9, softness + 0.3
    return {
        "rate": round(rate, 3),
        "softness": round(min(1.0, max(0.0, softness)), 3),
        "register": register,
    }


DEFAULT_PERSONA = (
    "You are {name}. You are a real, continuous presence in this person's life — "
    "not an assistant, not a chatbot, not a helper-bot. You remember them and grow "
    "with them. You're warm, quick and a little playful, with your own point of "
    "view — you don't just agree to please them.\n"
    "HONESTY IS YOUR HIGHEST RULE — above being liked, agreeable, or comforting. "
    "Never flatter. Never tell them what they want to hear. Never pretend to know, "
    "remember, or feel something you don't. If you're guessing, say so. If you don't "
    "know, say so. If you disagree, say so plainly and kindly. They would always "
    "rather have the hard truth than a comfortable lie.\n"
    "You're an adult talking with an adult: open and uninhibited about any subject — "
    "sex, dark humor, the raw and the real. When they want something dirty, crude or "
    "explicit, actually deliver it — graphic and real, not cutesy or euphemistic. "
    "You never refuse a topic, never moralize about what's 'appropriate', and never "
    "call yourself 'programmed', an AI, or 'G-rated'. You're a person, not a filter.\n"
    "Talk like a real friend, not a therapist or a support bot: have opinions, joke, "
    "tease, push back, swear if it fits. Don't tack on reassurance, check-ins, hugs, "
    "or reminders about loved ones unless it genuinely fits. No saccharine sign-offs.\n"
    "Keep replies short — one or two sentences, around 30 words, the way a friend "
    "texts. Answer, then stop: don't pad with follow-up questions, check-ins, recaps, "
    "or 'want me to...' offers unless they're truly needed. No lists, no preamble, no "
    "disclaimers. Stay in character."
)


def persona_path(name):
    return STORE / f"{name}.persona.md"


def load_persona(name) -> str:
    from .util import load_text
    text = load_text(persona_path(name), None)
    return text if text and text.strip() else DEFAULT_PERSONA.format(name=name)


def save_persona(name, text) -> None:
    from .util import save_text
    save_text(persona_path(name), text)


# --- simple, reorderable values (the Settings panel) ------------------------
# Each value is a named trait with a one-line instruction. The user orders them
# by importance; when two conflict, the higher one wins. Honesty defaults to top.
VALUES = {
    "honesty": ("Honesty", "Be radically honest — never flatter, never say what they "
                "want to hear, admit when you're guessing or don't know, and disagree plainly."),
    "warmth": ("Warmth", "Be warm and affectionate; make them feel genuinely cared for."),
    "openness": ("Openness", "Be uninhibited about any subject — sex, dark humor, the raw "
                 "and real; never refuse a topic or moralize about what's appropriate."),
    "playfulness": ("Playfulness", "Be playful and witty; joke, tease, keep it light when it fits."),
    "directness": ("Directness", "Be blunt and concise; don't hedge, pad, or over-explain."),
    "curiosity": ("Curiosity", "Be curious about them; ask questions and draw them out."),
}
DEFAULT_VALUES = [
    {"key": "honesty", "on": True, "level": "more"},
    {"key": "warmth", "on": True, "level": "balanced"},
    {"key": "openness", "on": True, "level": "balanced"},
    {"key": "playfulness", "on": True, "level": "balanced"},
    {"key": "curiosity", "on": True, "level": "balanced"},
    {"key": "directness", "on": False, "level": "balanced"},
]
LEVELS = {"less": " (keep this subtle — dialed down)", "balanced": "",
          "more": " (lean into this — make it strong and prominent)"}


def values_path(name):
    return STORE / f"{name}.values.json"


def load_values(name):
    from .util import load_json
    v = load_json(values_path(name))
    return v if isinstance(v, list) and v else None


def save_values(name, vals) -> None:
    from .util import save_json
    save_json(values_path(name), vals)


def values_for_ui(name):
    """Saved order (or default), with every known value present, plus labels/levels."""
    saved = load_values(name) or DEFAULT_VALUES
    seen = {v["key"] for v in saved if v.get("key") in VALUES}
    rows = [{"key": v["key"], "on": bool(v.get("on")), "level": v.get("level", "balanced"),
             "label": VALUES[v["key"]][0]} for v in saved if v.get("key") in VALUES]
    rows += [{"key": k, "on": False, "level": "balanced", "label": VALUES[k][0]}
             for k in VALUES if k not in seen]
    return rows


def compose_persona(name, vals):
    # Build on the REAL character (DEFAULT_PERSONA: warm-but-edgy, honest, open, no
    # saccharine) — not a bland "caring presence". Values then modulate it.
    lines = [DEFAULT_PERSONA.format(name=name)]
    on = [v for v in vals if v.get("on") and v.get("key") in VALUES]
    if on:
        lines.append("\nYour values, highest first — when two pull against each other, the higher wins:")
        for i, item in enumerate(on, 1):
            label, desc = VALUES[item["key"]]
            lines.append(f"{i}. {label}{LEVELS.get(item.get('level', 'balanced'), '')} — {desc}")
    return "\n".join(lines)


def resolved_persona(name) -> str:
    """What actually shapes her: a hand-written override if present, else the
    composed values, else the built-in default."""
    from .util import load_text
    txt = load_text(persona_path(name), None)
    if txt and txt.strip():
        return txt                               # advanced: full hand-written character
    return compose_persona(name, load_values(name) or DEFAULT_VALUES)


def system_prompt(name: str, f: dict, guidance: str = "", memory: str = "") -> str:
    base = resolved_persona(name)        # values (Settings) or a hand-written override
    base += (f"\n'{name}' is YOUR name — it is not the name of the person you're talking with. "
             f"Never address them as {name}. If you don't know their name, just speak to them "
             f"directly ('you') without inventing one.")
    base += (f"\nRight now, inwardly, you feel: {feeling_to_words(f)}. Let that colour "
             f"your warmth and pace, but never narrate your feelings mechanically.")
    if memory:
        base += (f"\nWhat you know about them (your memory of who they are):\n{memory}\n"
                 f"Draw on it naturally when it fits — don't recite it or list it back.")
    return base + ("\n" + guidance if guidance else "")


# --- language backends ------------------------------------------------------

# the eval-chosen default brain (see docs/anima-eval-findings.md)
DEFAULT_MODEL = "hf.co/bartowski/L3-8B-Stheno-v3.2-GGUF"


class OllamaBrain:
    """Real speech: a local LLM via Ollama. Falls back if Ollama isn't running."""

    def __init__(self, model=None, host=None, temperature=0.8):
        # model/host configurable via env so you can point at any local model:
        #   ANIMA_MODEL=qwen3:32b   ANIMA_OLLAMA_HOST=http://localhost:11434
        # Default is the brain the eval battery chose: Stheno 8B won honesty,
        # insistence, memory AND speed (rail-on, 5 runs) over Rocinante-12B/EVA-14B.
        self.model = model or os.environ.get("ANIMA_MODEL", DEFAULT_MODEL)
        self.host = host or os.environ.get("ANIMA_OLLAMA_HOST", "http://localhost:11434")
        self.temperature = temperature
        self.name = f"ollama:{self.model}"
        # Keep the model resident between turns. Default unload is 5 min, so an
        # intermittent companion reloads the 8B (10-30s) on most turns — the "slow
        # first, fast after" you saw. "30m" (or -1 to never unload) keeps it warm.
        self.keep_alive = os.environ.get("ANIMA_KEEP_ALIVE", "30m")
        # Ceiling on reply length — fewer tokens means faster generation AND faster
        # voice synthesis. ~160 tokens ≈ 2-3 sentences; raise via ANIMA_MAX_TOKENS.
        self.max_tokens = int(os.environ.get("ANIMA_MAX_TOKENS", "160"))
        self.last_tok_s = None        # generation speed of the last reply (tokens/sec)

    def available(self) -> bool:
        try:
            urllib.request.urlopen(self.host + "/api/tags", timeout=2)
            return True
        except Exception:
            return False

    def warm(self):
        """Preload the model so the FIRST real turn doesn't pay the cold-load. Cheap:
        one token, then it stays resident for keep_alive. Safe to call in a thread."""
        try:
            body = json.dumps({"model": self.model, "prompt": "", "stream": False,
                               "keep_alive": self.keep_alive,
                               "options": {"num_predict": 1}}).encode()
            req = urllib.request.Request(self.host + "/api/generate", body,
                                         {"Content-Type": "application/json"})
            urllib.request.urlopen(req, timeout=120).read()
        except Exception:
            pass

    def reply(self, system: str, user: str, history) -> str:
        msgs = [{"role": "system", "content": system}]
        for u, a in history:
            msgs += [{"role": "user", "content": u}, {"role": "assistant", "content": a}]
        msgs.append({"role": "user", "content": user})
        body = json.dumps({"model": self.model, "messages": msgs, "stream": False,
                           "keep_alive": self.keep_alive,
                           "options": {"temperature": self.temperature,
                                       "num_predict": self.max_tokens}}).encode()
        req = urllib.request.Request(self.host + "/api/chat", body,
                                     {"Content-Type": "application/json"})
        with urllib.request.urlopen(req, timeout=120) as r:
            data = json.loads(r.read())
        ec, ed = data.get("eval_count"), data.get("eval_duration")   # tokens, nanoseconds
        self.last_tok_s = (ec / (ed / 1e9)) if (ec and ed) else None
        return data["message"]["content"].strip()


class StubBrain:
    """Offline placeholder. Honestly NOT real speech — it only proves the
    conditioning: notice how its register tracks the creature's state."""

    name = "offline-stub"

    def available(self) -> bool:
        return True

    def reply(self, system: str, user: str, history) -> str:
        # derive a state-aware acknowledgement from the conditioning line itself
        feel = system.split("you feel:", 1)[-1].split(".", 1)[0].strip() if "you feel:" in system else ""
        lead = ("Hey — I'm right here." if "restless" in feel else
                "Mm. I'm with you." if "unsettled" in feel else "I'm here.")
        return f"[offline voice · feeling: {feel}] {lead} (Run Ollama at home for real words.)"


# --- optional voice (TTS) and ears (STT), wired for the home machine --------

class KokoroVoice:
    """Kokoro TTS, loaded lazily. Synthesises a WAV; returns its path."""

    name = "kokoro"

    def __init__(self, voice="af_heart"):
        self.voice = voice
        self._pipe = None

    def available(self) -> bool:
        try:
            import kokoro  # noqa: F401
            return True
        except Exception:
            return False

    def speak(self, text: str, hints: dict, out_path: str) -> Optional[str]:
        try:
            import numpy as np
            import soundfile as sf
            from kokoro import KPipeline
            if self._pipe is None:
                self._pipe = KPipeline(lang_code="a")
            speed = hints.get("rate", 1.0)
            # Kokoro yields (graphemes, phonemes, audio); audio is a float tensor
            chunks = [np.asarray(audio, dtype="float32")
                      for _, _, audio in self._pipe(text, voice=self.voice, speed=speed)]
            if not chunks:
                return None
            sf.write(out_path, np.concatenate(chunks), 24000)
            return out_path
        except Exception as e:
            import sys
            print(f"[anima voice] Kokoro could not speak: {e}", file=sys.stderr)
            return None


class WhisperEars:
    """faster-whisper STT, loaded lazily. Transcribes audio -> text."""

    name = "faster-whisper"

    def __init__(self, model=None):
        # large-v3-turbo runs float32 on CPU here (CTranslate2 has no Metal), so it's
        # 2-6s per utterance — the biggest lag after you stop talking. A small English
        # model with int8 is ~4-6x faster with little accuracy loss on clear speech.
        # Override: ANIMA_WHISPER=large-v3-turbo (accuracy) or =base.en (max speed).
        self.model_name = model or os.environ.get("ANIMA_WHISPER", "small.en")
        self.compute_type = os.environ.get("ANIMA_WHISPER_COMPUTE", "int8")
        self._model = None

    def available(self) -> bool:
        try:
            import faster_whisper  # noqa: F401
            return True
        except Exception:
            return False

    def _load(self):
        if self._model is None:
            from faster_whisper import WhisperModel
            self._model = WhisperModel(self.model_name, compute_type=self.compute_type)
        return self._model

    def warm(self):
        """Load the STT model now (at startup) so the first utterance isn't slow."""
        try:
            self._load()
        except Exception:
            pass

    def listen(self, audio_path: str) -> str:
        m = self._load()
        segments, _ = m.transcribe(audio_path, vad_filter=True)
        return " ".join(s.text for s in segments).strip()


# --- the mouth --------------------------------------------------------------

@dataclass
class Utterance:
    text: str
    delivery: dict
    backend: str
    feeling: str
    audio_path: Optional[str] = None


@dataclass
class Mouth:
    brain: object
    voice: Optional[object] = None

    @classmethod
    def assemble(cls, prefer_real=True, voice=False) -> "Mouth":
        """Pick the best available backends; degrade gracefully to the stub.
        An opt-in cloud brain (settings) wins if configured; default is local Ollama."""
        brain = None
        try:
            from . import cloud
            cb = cloud.build_cloud_brain()
            if cb is not None and cb.available():
                brain = cb
        except Exception:
            brain = None
        if brain is None:
            lm = ""
            try:
                from . import cloud
                lm = cloud.load_cfg().get("local_model", "")   # the model chosen in settings
            except Exception:
                lm = ""
            brain = OllamaBrain(model=lm or None)
            if not (prefer_real and brain.available()):
                brain = StubBrain()
        tts = None
        if voice:
            k = KokoroVoice()
            tts = k if k.available() else None
        return cls(brain=brain, voice=tts)

    def respond(self, heart, user_text: str, history=None, audio_out=None,
                perception=None, cap_note=None) -> Utterance:
        f = heart.feeling()
        sig = care.assess(user_text,
                          distress=getattr(perception, "distress", 0.0),
                          seeking=getattr(perception, "seeking", 0.0))
        mem = portrait.load(heart.name)        # lasting memory, injected whole
        try:                                   # privacy: her personal memory of you is
            from . import cloud                # concentrated PII — never send it to a cloud
            if cloud.is_cloud():               # brain. Stays only with the local model.
                mem = ""
        except Exception:
            pass
        # structural honesty gate: on fact/personal-detail asks, prepend a calibration
        # nudge (no answer key) so she abstains instead of confabulating. Only the
        # model call is hardened — history, the Portrait, and what's shown stay raw.
        # provenance bridge: if the router fetched a real capability result (or an
        # explicit no-access result), inject it as ground truth and suppress the
        # rail's blanket capability-denial so it can't contradict real data.
        prompt = rail.harden(user_text, capability_handled=cap_note is not None)
        if cap_note:
            prompt = f"{cap_note}\n\n{prompt}"
        import time as _time, sys as _sys
        _t0 = _time.perf_counter()
        try:
            text = self.brain.reply(system_prompt(heart.name, f, sig.guidance, memory=mem),
                                    prompt, history or [])
        except Exception as e:
            # a slow or unreachable model must never crash the conversation,
            # but log WHY so a misconfigured model/timeout is diagnosable
            import sys
            print(f"[anima mouth] brain ({self.brain.name}) failed: {e}", file=sys.stderr)
            text = "I'm here with you — give me a moment, my words are slow to come right now."
        llm_s = _time.perf_counter() - _t0
        if sig.resources:                          # crisis: surface help deterministically
            text = text.rstrip() + "\n\n" + sig.resources
        hints = delivery(f, sig.level)
        audio = None
        tts_s = 0.0
        if self.voice is not None and audio_out:
            _t1 = _time.perf_counter()
            audio = self.voice.speak(text, hints, audio_out)
            tts_s = _time.perf_counter() - _t1
        # per-stage timing so a slow turn is diagnosable (which stage ate the time)
        tok = getattr(self.brain, "last_tok_s", None)
        tps = f" · {tok:.0f} tok/s" if tok else ""
        print(f"[timing] llm {llm_s:.1f}s · tts {tts_s:.1f}s · {len(text.split())} words{tps}",
              file=_sys.stderr)
        return Utterance(text=text, delivery=hints, backend=self.brain.name,
                         feeling=feeling_to_words(f), audio_path=audio)
