#!/usr/bin/env python3
"""generate_total_scenario_matrix — inventory the REAL product and emit the Total Scenario Matrix.

Level-0 coverage (the foundation). Writes the inventory bundle + the matrix + a human coverage report:
  reports/user_surface_inventory.json
  reports/control_inventory.json
  reports/api_inventory.json
  reports/feature_to_scenario_matrix.json
  reports/scenario_matrix.json
  reports/scenario_coverage.md
No invented surfaces or controls — everything is discovered from the live product.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))
REPORTS = ROOT / "reports"


def main() -> int:
    from anima.scenarios import inventory, generator

    inv = inventory.full_inventory()
    matrix = generator.generate(inv)
    REPORTS.mkdir(exist_ok=True)

    (REPORTS / "user_surface_inventory.json").write_text(json.dumps(inv["surfaces"], indent=2))
    (REPORTS / "control_inventory.json").write_text(json.dumps(inv["controls"], indent=2))
    (REPORTS / "api_inventory.json").write_text(json.dumps(inv["routes"], indent=2))
    (REPORTS / "scenario_matrix.json").write_text(json.dumps(matrix, indent=2))

    # feature -> scenario mapping (every contract gets its scenario id)
    feat_map = {f["feature"]: ["trt_contract_%s" % f["feature"]] for f in inv["contracts"]}
    (REPORTS / "feature_to_scenario_matrix.json").write_text(json.dumps(feat_map, indent=2))

    c, mc = inv["counts"], matrix["counts"]
    ctrl_ids = {x["control_id"] for v in inv["controls"].values() for x in v}
    scen_ctrl = {s["control_id"] for s in matrix["scenarios"] if s.get("control_id")}
    md = [
        "# VERA TOTAL REALITY — LEVEL 0 COVERAGE (inventory + scenario matrix)\n",
        "## Real product inventory",
        "- Surfaces inventoried: **%d** (served: %d/%d)" % (c["surfaces"], c["surfaces_served"], c["surfaces"]),
        "- Controls inventoried: **%d**" % c["controls"],
        "- API routes inventoried: **%d** (GET %d / POST %d)" % (c["routes"], c["routes_get"], c["routes_post"]),
        "- Feature contracts mapped: **%d**" % c["contracts"],
        "\n## Scenario matrix (finite behaviour classes, equivalence-reduced)",
        "- Scenario classes generated: **%d**" % mc["total"],
        "- Fully classified (no UNKNOWN axis): **%d / %d**" % (mc["fully_classified"], mc["total"]),
        "- By kind: %s" % mc["by_kind"],
        "- By coverage level: %s" % mc["by_level"],
        "- Critical (Level 1): %d · Adversarial (Level 7): %d" % (mc["critical"], mc["adversarial"]),
        "\n## Hard rules",
        "- Every visible control has a scenario: **%d / %d**" % (len(ctrl_ids & scen_ctrl), len(ctrl_ids)),
        "- Every feature contract has a scenario: **%d / %d**" % (len(feat_map), c["contracts"]),
        "- Every surface is served: **%d / %d**" % (c["surfaces_served"], c["surfaces"]),
        "\n_Generated by scripts/generate_total_scenario_matrix.py — Level 0 of the Total Reality Test._",
    ]
    (REPORTS / "scenario_coverage.md").write_text("\n".join(md) + "\n")

    print("TOTAL SCENARIO MATRIX generated:")
    print("  surfaces=%d controls=%d routes=%d contracts=%d -> scenarios=%d (all classified=%s)"
          % (c["surfaces"], c["controls"], c["routes"], c["contracts"], mc["total"],
             mc["fully_classified"] == mc["total"]))
    print("  reports/scenario_matrix.json + scenario_coverage.md + 4 inventory files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
